#apollo:
#  bootstrap:
#    enabled: true
#    # will inject 'application' and 'TEST1.apollo' namespaces in bootstrap phase
#    namespaces: application,TEST1.apollo,application.yaml

server:
  port: 7070 # 避免和本地的 Apollo Portal 端口冲突

app:
  id: user-test-demo  # 使用的 Apollo 的项目（应用）编号
apollo:
  meta: http://127.0.0.1:8080 # Apollo Meta Server 地址
  bootstrap:
    enabled: true # 是否开启 Apollo 配置预加载功能。默认为 false。
    eagerLoad:
      enable: true # 是否开启 Apollo 支持日志级别的加载时机。默认为 false。
#    namespaces: application,TEST1.test-public # 使用的 Apollo 的命名空间，默认为 application。
    # 哪个在前，哪个的优先级高
    namespaces: TEST1.test-public,application # 使用的 Apollo 的命名空间，默认为 application。


