spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ApolloConfigDB?characterEncoding=utf8
    username: root
    password: root123

ctrip:
  appid: 100003171

server:
  port: 8080

logging:
  file: /opt/application/applogs/apollo/apollo-configservice.log
